const jojoCharacters = [
  // ジョジョの奇妙な冒険のキャラクター一覧
  // 勇敢・正義感タイプ
  {
    id: 1,
    name: "ジョナサン・ジョースター",
    age: 20,
    origin: "part1",
    originText: "第1部 ファントムブラッド",
    personality: "brave",
    personalityText: "勇敢・正義感タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id01.jpg",
    description:
      "ジョースター家の跡取り。紳士的な性格と不屈の精神の持ち主。波紋を使いディオと戦う。",
  },
  {
    id: 2,
    name: "シーザー・A・ツェペリ",
    age: 20,
    origin: "part2",
    originText: "第2部 戦闘潮流",
    personality: "brave",
    personalityText: "勇敢・正義感タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id02.jpg",
    description:
      "波紋の使い手。誇り高く、仲間思いで友情に厚い。柱の男との戦いで命を賭ける。",
  },
  {
    id: 3,
    name: "ジャン＝ピエール・ポルナレフ",
    age: 22,
    origin: "part3",
    originText: "第3部 スターダストクルセイダース",
    personality: "brave",
    personalityText: "勇敢・正義感タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id03.jpg",
    description:
      "フランス出身のスタンド使い。正義感が強く、仲間のために体を張る熱血漢。",
  },
  {
    id: 4,
    name: "東方仗助",
    age: 16,
    origin: "part4",
    originText: "第4部 ダイヤモンドは砕けない",
    personality: "brave",
    personalityText: "勇敢・正義感タイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "male",
    genderText: "男",
    image: "image/id04.jpg",
    description:
      "杜王町の高校生。仲間思いで、困っている人を放っておけない優しい性格。",
  },
  {
    id: 5,
    name: "ブローノ・ブチャラティ",
    age: 20,
    origin: "part5",
    originText: "第5部 黄金の風",
    personality: "brave",
    personalityText: "勇敢・正義感タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "male",
    genderText: "男",
    image: "image/id05.jpg",
    description:
      "ギャング組織のリーダーで、冷静で誠実。仲間を守るために命を懸ける。",
  },
  {
    id: 6,
    name: "空条徐倫",
    age: 19,
    origin: "part6",
    originText: "第6部 ストーンオーシャン",
    personality: "brave",
    personalityText: "勇敢・正義感タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "female",
    genderText: "女",
    image: "image/id06.jpg",
    description:
      "空条承太郎の娘。逆境にも負けない強い正義感と、仲間への思いやりを持つ。",
  },

  // クール・冷静沈着タイプ
  {
    id: 7,
    name: "ウィル・A・ツェペリ",
    age: 50,
    origin: "part1",
    originText: "第1部 ファントムブラッド",
    personality: "cool",
    personalityText: "クール・冷静沈着タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "male",
    genderText: "男",
    image: "image/id07.jpg",
    description: "波紋の師。冷静沈着で経験豊富、ジョナサンの良き指導者。",
  },
  {
    id: 8,
    name: "リサリサ",
    age: 50,
    origin: "part2",
    originText: "第2部 戦闘潮流",
    personality: "cool",
    personalityText: "クール・冷静沈着タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "female",
    genderText: "女",
    image: "image/id08.jpg",
    description:
      "波紋の達人でジョセフの師。常に冷静な判断力と厳しさで弟子を導く。",
  },
  {
    id: 9,
    name: "空条承太郎",
    age: 17,
    origin: "part3",
    originText: "第3部 スターダストクルセイダース",
    personality: "cool",
    personalityText: "クール・冷静沈着タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id09.jpg",
    description: "無口でクールな性格。的確な判断力と強いリーダーシップを持つ。",
  },
  {
    id: 10,
    name: "岸辺露伴",
    age: 20,
    origin: "part4",
    originText: "第4部 ダイヤモンドは砕けない",
    personality: "cool",
    personalityText: "クール・冷静沈着タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "male",
    genderText: "男",
    image: "image/id10.jpg",
    description:
      "人気漫画家で観察眼が鋭い。感情的になりやすいが、冷静な判断力も持つ。",
  },
  {
    id: 11,
    name: "レオーネ・アバッキオ",
    age: 21,
    origin: "part5",
    originText: "第5部 黄金の風",
    personality: "cool",
    personalityText: "クール・冷静沈着タイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "male",
    genderText: "男",
    image: "image/id11.jpg",
    description: "元警官で冷静沈着。仲間に厳しいが、その分信頼も厚い。",
  },
  {
    id: 12,
    name: "ウェザー・リポート",
    age: 22,
    origin: "part6",
    originText: "第6部 ストーンオーシャン",
    personality: "cool",
    personalityText: "クール・冷静沈着タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id12.jpg",
    description: "記憶喪失の謎多き男。寡黙で冷静、状況判断に優れる。",
  },

  // お調子者・トリックスタータイプ
  {
    id: 13,
    name: "ロバート・E・O・スピードワゴン",
    age: 25,
    origin: "part1",
    originText: "第1部 ファントムブラッド",
    personality: "trickster",
    personalityText: "お調子者・トリックスタータイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "male",
    genderText: "男",
    image: "image/id13.jpg",
    description: "下町出身の義侠心あふれる快男児。明るくムードメーカー的存在。",
  },
  {
    id: 14,
    name: "ジョセフ・ジョースター",
    age: 18,
    origin: "part2",
    originText: "第2部 戦闘潮流",
    personality: "trickster",
    personalityText: "お調子者・トリックスタータイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id14.jpg",
    description:
      "ジョナサンの孫。トリッキーな戦い方が得意で、「次にお前は〜」が口癖。柱の男との戦いで活躍。",
  },
  {
    id: 15,
    name: "イギー",
    age: 1,
    origin: "part3",
    originText: "第3部 スターダストクルセイダース",
    personality: "trickster",
    personalityText: "お調子者・トリックスタータイプ",
    bodyType: "chubby",
    bodyTypeText: "ぽっちゃり",
    gender: "male",
    genderText: "男",
    image: "image/id15.jpg",
    description:
      "コーヒーガム好きな犬のスタンド使い。気まぐれでずる賢いが根は仲間思い。",
  },
  {
    id: 16,
    name: "虹村億泰",
    age: 16,
    origin: "part4",
    originText: "第4部 ダイヤモンドは砕けない",
    personality: "trickster",
    personalityText: "お調子者・トリックスタータイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id16.jpg",
    description: "単純で明るい性格。思い込みが激しいが憎めないムードメーカー。",
  },
  {
    id: 17,
    name: "グイード・ミスタ",
    age: 18,
    origin: "part5",
    originText: "第5部 黄金の風",
    personality: "trickster",
    personalityText: "お調子者・トリックスタータイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "male",
    genderText: "男",
    image: "image/id17.jpg",
    description: "銃使いのスタンド使い。楽天的で明るく、仲間を和ませる存在。",
  },
  {
    id: 18,
    name: "エンポリオ・アルニーニョ",
    age: 11,
    origin: "part6",
    originText: "第6部 ストーンオーシャン",
    personality: "trickster",
    personalityText: "お調子者・トリックスタータイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "male",
    genderText: "男",
    image: "image/id18.jpg",
    description:
      "少年囚人で知恵者。ピンチを機転で乗り切るトリックスター的存在。",
  },

  // 熱血・情熱家タイプ
  {
    id: 19,
    name: "ダイアー",
    age: 35,
    origin: "part1",
    originText: "第1部 ファントムブラッド",
    personality: "passion",
    personalityText: "熱血・情熱家タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id19.jpg",
    description: "波紋使いの一人で、熱血かつストレートな性格。",
  },
  {
    id: 20,
    name: "ルドル・フォン・シュトロハイム",
    age: 35,
    origin: "part2",
    originText: "第2部 戦闘潮流",
    personality: "passion",
    personalityText: "熱血・情熱家タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id20.jpg",
    description: "ドイツ軍人で情熱的。自らの信念と誇りを持って戦う。",
  },
  {
    id: 21,
    name: "モハメド・アヴドゥル",
    age: 28,
    origin: "part3",
    originText: "第3部 スターダストクルセイダース",
    personality: "passion",
    personalityText: "熱血・情熱家タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id21.jpg",
    description: "情熱と誠実さが持ち味のスタンド使い。仲間を思いやる熱血漢。",
  },
  {
    id: 22,
    name: "虹村形兆",
    age: 18,
    origin: "part4",
    originText: "第4部 ダイヤモンドは砕けない",
    personality: "passion",
    personalityText: "熱血・情熱家タイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "male",
    genderText: "男",
    image: "image/id22.jpg",
    description: "億泰の兄で情熱的。弟思いで信念を貫く熱血な一面がある。",
  },
  {
    id: 23,
    name: "ナランチャ・ギルガ",
    age: 17,
    origin: "part5",
    originText: "第5部 黄金の風",
    personality: "passion",
    personalityText: "熱血・情熱家タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "male",
    genderText: "男",
    image: "image/id23.jpg",
    description: "素直で情熱的な少年。仲間を守るために全力を尽くす。",
  },
  {
    id: 24,
    name: "エルメェス・コステロ",
    age: 21,
    origin: "part6",
    originText: "第6部 ストーンオーシャン",
    personality: "passion",
    personalityText: "熱血・情熱家タイプ",
    bodyType: "glamorous",
    bodyTypeText: "グラマー",
    gender: "female",
    genderText: "女",
    image: "image/id24.jpg",
    description: "明るく負けず嫌い。仲間思いで情熱的な女性スタンド使い。",
  },

  // 狡猾・野心家タイプ
  {
    id: 25,
    name: "ディオ・ブランドー",
    age: 20,
    origin: "part1",
    originText: "第1部 ファントムブラッド",
    personality: "ambitious",
    personalityText: "狡猾・野心家タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "male",
    genderText: "男",
    image: "image/id25.jpg",
    description:
      "強い野心と狡猾さを持つ。ジョースター家を乗っ取ろうと暗躍する。",
  },
  {
    id: 26,
    name: "カーズ",
    age: 2000,
    origin: "part2",
    originText: "第2部 戦闘潮流",
    personality: "ambitious",
    personalityText: "狡猾・野心家タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id26.jpg",
    description: "柱の男のリーダー。冷徹で野心家、究極生命体を目指す。",
  },
  {
    id: 27,
    name: "DIO",
    age: 100,
    origin: "part3",
    originText: "第3部 スターダストクルセイダース",
    personality: "ambitious",
    personalityText: "狡猾・野心家タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id27.jpg",
    description:
      "吸血鬼となり永遠の命を得たディオ。世界征服を企む極めて野心的な存在。",
  },
  {
    id: 28,
    name: "吉良吉影",
    age: 33,
    origin: "part4",
    originText: "第4部 ダイヤモンドは砕けない",
    personality: "ambitious",
    personalityText: "狡猾・野心家タイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "male",
    genderText: "男",
    image: "image/id28.jpg",
    description: "静かに暮らすことを望むが、冷酷かつ狡猾な連続殺人鬼。",
  },
  {
    id: 29,
    name: "ディアボロ",
    age: 33,
    origin: "part5",
    originText: "第5部 黄金の風",
    personality: "ambitious",
    personalityText: "狡猾・野心家タイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id29.jpg",
    description:
      "ギャング組織のボス。自らの地位を守るため、残忍かつ狡猾に行動する。",
  },
  {
    id: 30,
    name: "エンリコ・プッチ",
    age: 39,
    origin: "part6",
    originText: "第6部 ストーンオーシャン",
    personality: "ambitious",
    personalityText: "狡猾・野心家タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "male",
    genderText: "男",
    image: "image/id30.jpg",
    description:
      "神父でありながら強い野心と計画性を持ち、己の理想のために暗躍する。",
  },

  // 純粋・天然タイプ
  {
    id: 31,
    name: "エリナ・ペンドルトン",
    age: 20,
    origin: "part1",
    originText: "第1部 ファントムブラッド",
    personality: "pure",
    personalityText: "純粋・天然タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "female",
    genderText: "女",
    image: "image/id31.jpg",
    description: "心優しく純粋。ジョナサンを一途に思い続ける女性。",
  },
  {
    id: 32,
    name: "スージーQ",
    age: 20,
    origin: "part2",
    originText: "第2部 戦闘潮流",
    personality: "pure",
    personalityText: "純粋・天然タイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "female",
    genderText: "女",
    image: "image/id32.jpg",
    description: "ジョセフの妻。明るく天然な性格で場を和ませる。",
  },
  {
    id: 33,
    name: "ホル・ホース",
    age: 23,
    origin: "part3",
    originText: "第3部 スターダストクルセイダース",
    personality: "pure",
    personalityText: "純粋・天然タイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "male",
    genderText: "男",
    image: "image/id33.jpg",
    description: "どこか抜けていて憎めない性格。自由奔放なガンマン。",
  },
  {
    id: 34,
    name: "山岸由花子",
    age: 16,
    origin: "part4",
    originText: "第4部 ダイヤモンドは砕けない",
    personality: "pure",
    personalityText: "純粋・天然タイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "female",
    genderText: "女",
    image: "image/id34.jpg",
    description: "康一くんを一途に思い続ける。独特で純粋な愛情を持つ。",
  },
  {
    id: 35,
    name: "トリッシュ・ウナ",
    age: 15,
    origin: "part5",
    originText: "第5部 黄金の風",
    personality: "pure",
    personalityText: "純粋・天然タイプ",
    bodyType: "glamorous",
    bodyTypeText: "グラマー",
    gender: "female",
    genderText: "女",
    image: "image/id35.jpg",
    description: "ギャングのボスの娘。繊細で天然な側面を持つ。",
  },
  {
    id: 36,
    name: "フー・ファイターズ",
    age: 0,
    origin: "part6",
    originText: "第6部 ストーンオーシャン",
    personality: "pure",
    personalityText: "純粋・天然タイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "female",
    genderText: "女",
    image: "image/id36.jpg",
    description:
      "知識欲旺盛で純粋な知的好奇心にあふれるプランクトンのスタンド。",
  },

  // 仲間思い・サポートタイプ
  {
    id: 37,
    name: "ウォン・チェン",
    age: 40,
    origin: "part1",
    originText: "第1部 ファントムブラッド",
    personality: "support",
    personalityText: "仲間思い・サポートタイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "male",
    genderText: "男",
    image: "image/id37.jpg",
    description: "スピードワゴン財団のメンバー。ジョースター家を陰で支える。",
  },
  {
    id: 38,
    name: "メッシーナ",
    age: 30,
    origin: "part2",
    originText: "第2部 戦闘潮流",
    personality: "support",
    personalityText: "仲間思い・サポートタイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id38.jpg",
    description: "波紋使いの指導者の一人。仲間を支えるサポート役。",
  },
  {
    id: 39,
    name: "花京院典明",
    age: 17,
    origin: "part3",
    originText: "第3部 スターダストクルセイダース",
    personality: "support",
    personalityText: "仲間思い・サポートタイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "male",
    genderText: "男",
    image: "image/id39.jpg",
    description: "知的で物静か。仲間のために命を賭けて支えることもいとわない。",
  },
  {
    id: 40,
    name: "広瀬康一",
    age: 15,
    origin: "part4",
    originText: "第4部 ダイヤモンドは砕けない",
    personality: "support",
    personalityText: "仲間思い・サポートタイプ",
    bodyType: "slim",
    bodyTypeText: "スリム",
    gender: "male",
    genderText: "男",
    image: "image/id40.jpg", 
    description:
      "誠実で真面目な高校生。強い責任感と友情を持ち、仲間を支える。エコーズの使い手。",
  },
  {
    id: 41,
    name: "パンナコッタ・フーゴ",
    age: 16,
    origin: "part5",
    originText: "第5部 黄金の風",
    personality: "support",
    personalityText: "仲間思い・サポートタイプ",
    bodyType: "normal",
    bodyTypeText: "普通",
    gender: "male",
    genderText: "男",
    image: "image/id41.jpg",
    description: "頭脳派で仲間思い。知恵と知識でチームをサポートする。",
  },
  {
    id: 42,
    name: "アナスイ",
    age: 23,
    origin: "part6",
    originText: "第6部 ストーンオーシャン",
    personality: "support",
    personalityText: "仲間思い・サポートタイプ",
    bodyType: "muscular",
    bodyTypeText: "筋肉質",
    gender: "male",
    genderText: "男",
    image: "image/id42.jpg",
    description: "徐倫に一途な想いを寄せ、献身的に支えるサポーター。",
  },
];
